app = "launchdate-backend"
primary_region = "sin"

[env]
SERVER_PORT = "8080"
SERVER_HOST = "0.0.0.0"
SERVER_ENVIRONMENT = "production"
GIN_MODE="release"
MONGODB_DATABASE = "launchdate_db"
LL2_URL_PREFIX = "https://ll.thespacedevs.com"
LL2_REQUEST_INTERVAL = "5"

[[services.http_checks]]
    interval = "30s"
    grace_period = "5s"
    method = "get"
    path = "/api/v1/health"
    protocol = "http"
    timeout = "2s"
    tls_skip_verify = false